pipeline:
  name: imagetodockerhub
  identifier: imagetodockerhub
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Gitconnector1
        repoName: webserver
        build: <+input>
  stages:
    - parallel:
        - stage:
            name: clonethecode
            identifier: clonethecode
            type: CI
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      type: Background
                      name: Background_1
                      identifier: Background_1
                      spec: {}
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
        - stage:
            name: build
            identifier: build
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Background
                      name: Background_1
                      identifier: Background_1
                      spec:
                        shell: Bash
                        command: echo "Hello World"
        - stage:
            name: testing
            identifier: testing
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Background
                      name: Background_1
                      identifier: Background_1
                      spec:
                        shell: Bash
                        command: hostname
    - stage:
        name: imagecreation
        identifier: imagecreation
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerconnector
                    repo: kharatramesh/vadapavimages
                    tags:
                      - pushimage
                    dockerfile: Dockerfile.
